import { ArrowUpRight, Info, MapPin, Sparkles, ThermometerSun } from "lucide-react";
import type { Forecast } from "@/types/forecast";
import { formatDateTime } from "@/lib/formatters";

export function ForecastHero({ forecast }: { forecast: Forecast }) {
  const spread = ((forecast.upperBound - forecast.lowerBound) / 2).toFixed(1);
  return <section className="relative isolate overflow-hidden rounded-2xl border border-sky-300/[0.14] bg-[#0b1b2d] p-5 shadow-[0_24px_80px_rgba(0,0,0,.2)] sm:p-7 lg:p-8">
    <div className="pointer-events-none absolute -right-20 -top-32 -z-10 h-80 w-80 rounded-full bg-sky-400/[0.08] blur-3xl"/><div className="pointer-events-none absolute right-[12%] top-1/2 -z-10 h-44 w-44 -translate-y-1/2 rounded-full border border-sky-300/[0.06] shadow-[0_0_80px_rgba(56,189,248,.07)]"/>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-5 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.17em] text-sky-300"><Sparkles size={13}/>Forecast Intelligence</div><div className="flex items-center gap-2 text-xs text-slate-400"><MapPin size={14} className="text-slate-400"/>{forecast.location}<span className="text-slate-700">/</span>{forecast.target}</div><h2 className="mt-2 text-lg font-medium tracking-tight text-white sm:text-xl">{forecast.target} forecast</h2></div><span className="rounded-md border border-white/[0.08] bg-white/[0.025] px-2.5 py-1.5 text-[10px] text-slate-400">{forecast.horizon} forecast horizon</span></div>
    <div className="mt-6 flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><div><div className="flex items-start"><span className="text-[62px] font-semibold leading-[.95] tracking-[-.065em] text-white sm:text-[76px]">{forecast.prediction.toFixed(1)}</span><span className="ml-1 mt-1 text-2xl font-medium text-slate-400">°C</span></div><div className="mt-4 flex flex-wrap items-center gap-x-3 gap-y-2 text-xs"><span className="text-slate-400">Expected range</span><span className="font-medium text-sky-200">{forecast.lowerBound.toFixed(1)}°C — {forecast.upperBound.toFixed(1)}°C</span><span className="rounded-full border border-indigo-300/15 bg-indigo-300/[0.06] px-2 py-0.5 text-[10px] text-indigo-200">±{spread}°C uncertainty</span><button type="button" aria-label="Prediction range represents estimated forecast uncertainty" title="Prediction range represents estimated forecast uncertainty." className="group relative rounded p-0.5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-sky-300"><Info size={13} className="text-slate-400"/><span role="tooltip" className="pointer-events-none absolute bottom-6 left-1/2 z-20 hidden w-48 -translate-x-1/2 rounded-md border border-white/10 bg-slate-900 px-2.5 py-2 text-left text-[10px] leading-4 text-slate-300 shadow-xl group-hover:block group-focus-visible:block">Prediction range represents estimated forecast uncertainty.</span></button></div><p className="mt-3 text-[10px] text-slate-400">Forecast issued · {formatDateTime(forecast.issueTime)}</p></div><div className="flex items-center gap-3 border-t border-white/[0.07] pt-4 sm:border-l sm:border-t-0 sm:pl-5 sm:pt-0"><span className="grid h-9 w-9 place-items-center rounded-lg bg-sky-300/[0.08] text-sky-300"><ThermometerSun size={18}/></span><div><p className="text-[10px] uppercase tracking-wider text-slate-400">Forecast Model</p><p className="mt-1 text-xs font-medium text-slate-200">{forecast.model}</p><p className="mt-0.5 text-[10px] text-slate-400">Version {forecast.modelVersion}</p></div><ArrowUpRight size={14} className="ml-4 text-slate-400"/></div></div>
  </section>;
}
